name: food_delivery
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  after_layout: ^1.2.0
  build_runner: ^2.7.0
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.10.0
  geocoding: ^4.0.0
  get_it: ^8.2.0
  go_router: ^16.2.0
  go_transitions: ^0.8.2
  google_fonts: ^6.3.0
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  location: ^8.0.1
  meta: ^1.16.0
  my_flutter_toolkit:
    git:
      url: https://github.com/AmrSalahDev/MyFlutterToolKit.git
      ref: main
  otp_resend_timer: ^1.0.0
  pinput: ^5.0.1
  rename: ^3.1.0
  sentry_flutter: ^9.6.0
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.10.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/food/
    - assets/images/restaurants/
    - assets/icons/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
        - asset: assets/fonts/Sen-Bold.ttf
        - asset: assets/fonts/Sen-ExtraBold.ttf
        - asset: assets/fonts/Sen-Medium.ttf
        - asset: assets/fonts/Sen-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
