name: food_delivery
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  after_layout: ^1.2.0
  animated_digit: ^3.3.1+2
  awesome_card: ^1.1.7
  bounce: ^1.0.2
  build_runner: ^2.7.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  change_app_package_name: ^1.5.0
  clarity_flutter: ^1.4.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_credit_card: ^4.1.0
  flutter_dotenv: ^6.0.0
  flutter_gen_runner: ^5.11.0
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.10.0
  geocoding: ^4.0.0
  get_it: ^8.2.0
  go_router: ^16.2.0
  go_transitions: ^0.8.2
  google_fonts: ^6.3.0
  group_button: ^5.3.4
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  location: ^8.0.1
  lottie: ^3.3.1
  meta: ^1.16.0
  my_flutter_toolkit:
    git:
      url: https://github.com/AmrSalahDev/MyFlutterToolKit.git
      ref: main
  otp_resend_timer: ^1.0.0
  pinput: ^5.0.1
  readmore: ^3.0.0
  rename: ^3.1.0
  scroll_to_hide: ^2.2.1
  sentry_flutter: ^9.6.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.10.0
  toastification: ^3.0.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: true


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/lottie/
    - assets/images/food/
    - assets/images/food/burger/
    - assets/images/food/pizza/
    - assets/images/food/pasta/
    - assets/images/food/sandwich/
    - assets/images/restaurants/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
        - asset: assets/fonts/Sen-Bold.ttf
        - asset: assets/fonts/Sen-ExtraBold.ttf
        - asset: assets/fonts/Sen-Medium.ttf
        - asset: assets/fonts/Sen-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
